### ISSUE TITLE
runtime error: index out of range

### ISSUE THREAD

**Issue by ghost** [Killeroo/Stitcher#4]
I get this error when running the command:
`Stitcher -cols 6 -name walk.png ./idle/` on osx

The walk directory contains 6 gif files in the format 01.gif..06.gif.

Full error message:

```
       (o\---/o)
        ( . . )
       _( (T) )_
      / /     \ \
     / /       \ \
     \_)       (_/
       \   _   /
       _)  |  (_
      (___,'.___)   [STITCHER] - SPRITESHEET GENERATOR VERSION 1.0

panic: runtime error: index out of range

goroutine 1 [running]:
main.saveNewImage(0xc420043c60, 0x0, 0x0, 0x6, 0x7ffeefbff307, 0x8, 0x0, 0x0)
	C:/Projects/Stitcher/stitcher.go:48 +0x922
main.main()
	C:/Projects/Stitcher/stitcher.go:259 +0x1049
```

**Comment by Killeroo** [comment]
Yeah Stitcher doesn't support GIFs, but I looked into it and it shouldn't be too hard to implement. I'm looking into a fix now

**Comment by Killeroo** [comment]
I've added support for GIFs in the latest [release](https://github.com/Killeroo/Stitcher/releases/tag/v1.1). It should fix the error you were seeing

**Comment by ghost** [comment]
Thanks!!
